[zh-CN]
  title = "幸福和富有的过一生"
  languageName = "中文"
  weight = 1
  contentdir = "content/zh-CN"

[en]
  title = "Happy and prosperous life."
  languageName = "English"
  weight = 2
  contentdir = "content/en"
