Description = "欢迎来到我的空间站，个人主要专注于软件开发，科技技术，云计算，加密货币。"
Keywords =  "云计算, 软件开发, 架构师, 思考, 读书, 笔记, 技术, 投资, 加密货币, 区块链"
Subtitle = "幸福和富有的过一生!"
AuthorImg = "/img/avatar.png"
AuthorName = "lizj3624"
Introduce = "幸福和富有的过一生!" 
DateFormat = "2006-01-02"
YearFormat = "2022年"
MonthFormat = "02-07"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/lizj3624/"

[[Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/li-zun-ju"
